In [122]:
import pandas as pd

# Load the uploaded Excel file to inspect its structure and contents
file_path = "./Deepcatch 2025-1-14.xlsx"
df = pd.read_excel(file_path, header=2)

# df = pd.read_excel(file_path, header=2, dtype=str)


# Display sheet names to understand the structure of the Excel file
df.columns

Index(['Unnamed: 0', '(실명)등록번호', '생년월일', '성별', '병리진단', 'Steatosis score',
       'Fibrosis stage', 'Ballooning/Inflammation Score', 'NAFLD Type',
       'Smoking',
       ...
       'Liver/Spleen Volume Ratio', 'Liver Index', 'Spleen Index',
       'mean HU(Liver) - mean HU(Spleen)', 'Liver/Spleen HU Ratio',
       'Liver Fat (PDFF)', 'Liver', 'Spleen (Volume)', 'Liver.1', 'Spleen'],
      dtype='object', length=314)

In [98]:
pd.reset_option("display.max_rows")
pd.reset_option("display.max_columns")
pd.reset_option("display.expand_frame_repr")
pd.options.display.max_columns = None

In [113]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [123]:
df["NAFLD Type"].value_counts(dropna=False)

NAFLD Type
NASH                 62
NAFL                 57
Probable NASH        46
Others (Cancer)      29
Others               27
Cirrhosis            26
NaN                  24
NAFL (+)             12
Probable NASH (+)     5
NASH (+)              3
Missing Biopsy        1
Name: count, dtype: int64

In [124]:
df["NAFLD Type"] = df["NAFLD Type"].fillna("None")

In [125]:
df["NAFLD Type"].value_counts(dropna=False)

NAFLD Type
NASH                 62
NAFL                 57
Probable NASH        46
Others (Cancer)      29
Others               27
Cirrhosis            26
None                 24
NAFL (+)             12
Probable NASH (+)     5
NASH (+)              3
Missing Biopsy        1
Name: count, dtype: int64

In [126]:
df.columns.tolist()

['Unnamed: 0',
 '(실명)등록번호',
 '생년월일',
 '성별',
 '병리진단',
 'Steatosis score',
 'Fibrosis stage',
 'Ballooning/Inflammation Score',
 'NAFLD Type',
 'Smoking',
 'HCC',
 'HCC_date',
 'LRE',
 'LRE_date',
 'Ascites',
 'Ascites_Date',
 'Varix bleeding',
 'VB_date',
 'HEP',
 'HEP_date',
 'HRS',
 'HRS_date',
 'LT',
 'LT_date',
 '사망일자',
 'CT_B date',
 'FS_date',
 'LSM',
 'CAP',
 'AST',
 'ALT',
 'T.bil',
 'PLT',
 'PT INR',
 'Alb',
 'Glucose',
 'HbA1c',
 'eGFR',
 'T.chol',
 'HDL',
 'LDL',
 'TG',
 'Weight',
 'Height',
 'BMI',
 'SBP (수축기 혈압) mmHg',
 'SBP (수축기 혈압)_date',
 'DBP (이완기 혈압) mmHg',
 'DBP (이완기 혈압)_date',
 'Waist (허리 둘레 cm)',
 'Waist (허리 둘레 cm)_date',
 '음주 여부',
 '술의 종류',
 '1회 음주량 (잔 혹은 병)',
 '음주 횟수 (회/주)',
 'CT_1y date',
 'FS_date.1',
 'LSM.1',
 'CAP.1',
 'AST.1',
 'ALT.1',
 'T.bil.1',
 'PLT.1',
 'PT INR.1',
 'Alb.1',
 'Glucose.1',
 'HbA1c.1',
 'eGFR.1',
 'T.chol.1',
 'HDL.1',
 'LDL.1',
 'TG.1',
 'Inbody_date',
 'Weight.1',
 'Height.1',
 'BMI.1',
 'CT_2y date',
 'FS_date.2',
 'LSM.2',
 'CAP.2',
 'AST.2',
 'ALT.2',
 'T.bil.2',
 'PLT.2',
 'PT INR.2',
 'Alb.2',
 'Glucose.2',
 'HbA1c.2',
 'eGFR.2',
 'T.chol.2',
 'HDL.2',
 'LDL.2',
 'TG.2',
 'Inbody_date.1',
 'Weight.2',
 'Height.2',
 'BMI.2',
 'CT_3y date',
 'FS_date.3',
 'LSM.3',
 'CAP.3',
 'AST.3',
 'ALT.3',
 'T.bil.3',
 'PLT.3',
 'PT INR.3',
 'Alb.3',
 'Glucose.3',
 'HbA1c.3',
 'eGFR.3',
 'T.chol.3',
 'HDL.3',
 'LDL.3',
 'TG.3',
 'Inbody_date.2',
 'Weight.3',
 'Height.3',
 'Unnamed: 117',
 'BMI.3',
 'CT_4y date',
 'FS_date.4',
 'LSM.4',
 'CAP.4',
 'AST.4',
 'ALT.4',
 'T.bil.4',
 'PLT.4',
 'PT INR.4',
 'Alb.4',
 'Glucose.4',
 'HbA1c.4',
 'eGFR.4',
 'T.chol.4',
 'HDL.4',
 'LDL.4',
 'TG.4',
 'Inbody_date.3',
 'Weight.4',
 'Height.4',
 'Unnamed: 139',
 'BMI.4',
 'CT_5y date',
 'FS_date.5',
 'LSM.5',
 'CAP.5',
 'AST.5',
 'ALT.5',
 'T.bil.5',
 'PLT.5',
 'PT INR.5',
 'Alb.5',
 'Glucose.5',
 'HbA1c.5',
 'eGFR.5',
 'T.chol.5',
 'HDL.5',
 'LDL.5',
 'TG.5',
 'Inbody_date.4',
 'Weight.5',
 'Height.5',
 'Unnamed: 161',
 'BMI.5',
 '당뇨병/당뇨병 전단계 유무',
 '고혈압유무',
 '이상지질혈증 유무',
 'Ischemic Heart Diseae 유무',
 'Cerebrovascualr disease 유무',
 'Nephropathy 유무',
 '당뇨병/당뇨병 전단계 유무.1',
 '고혈압유무.1',
 '이상지질혈증 유무.1',
 'Ischemic Heart Diseae 유무.1',
 'Cerebrovascualr disease 유무.1',
 'Nephropathy 유무.1',
 '당뇨병/당뇨병 전단계 유무.2',
 '고혈압유무.2',
 '이상지질혈증 유무.2',
 'Ischemic Heart Diseae 유무.2',
 'Cerebrovascualr disease 유무.2',
 'Nephropathy 유무.2',
 '당뇨병/당뇨병 전단계 유무.3',
 '고혈압유무.3',
 '이상지질혈증 유무.3',
 'Ischemic Heart Diseae 유무.3',
 'Cerebrovascualr disease 유무.3',
 'Nephropathy 유무.3',
 '당뇨병/당뇨병 전단계 유무.4',
 '고혈압유무.4',
 '이상지질혈증 유무.4',
 'Ischemic Heart Diseae 유무.4',
 'Cerebrovascualr disease 유무.4',
 'Nephropathy 유무.4',
 '당뇨병/당뇨병 전단계 유무.5',
 '고혈압유무.5',
 '이상지질혈증 유무.5',
 'Ischemic Heart Diseae 유무.5',
 'Cerebrovascualr disease 유무.5',
 'Nephropathy 유무.5',
 'Last fu_date',
 'Metformin',
 'Metformin_date',
 'Dipeptidyl peptidase 4 inhibitor',
 'Dipeptidyl peptidase 4 inhibitor_date',
 'Sulfonylurea',
 'Sulfonylurea_date',
 'Thiazolidinedione',
 'Thiazolidinedione_date',
 'α glucosidase inhibitor',
 'α glucosidase inhibitor-date',
 'Meglitinide',
 'Meglitinide_date',
 'SGLT2i',
 'SGLT2i_date',
 'GLP1 receptor agonist',
 'GLP1 receptor agonist_date',
 'Insulin',
 'Insulin_date',
 'ACEi inhibitor',
 'ACEi inhibitor_date',
 'ARB',
 'ARB_date',
 'β-adrenergic blocking agents',
 'β-adrenergic blocking agents_date',
 'α-adrenergic blocking agents',
 'α-adrenergic blocking agents_date',
 'Cacium channel blocker',
 'Cacium channel blocker_date',
 'Diuretics_date',
 'Diuretics',
 'Statin',
 'Statin_date',
 'fibric acids (fenofibrate)',
 'fibric acids (fenofibrate)_date',
 'Azetidinone(Cholesterol absorption inhibitors, ezetimibe)',
 'VFI',
 'SFI',
 'SMI',
 'Height 2',
 'BMI[kg/m2]',
 'Circumference [mm]',
 'Max Length (L-R) [mm]',
 'Max Length (A-P) [mm]',
 'Skin',
 'Bone',
 'Muscle',
 'AVF (Single Volume)',
 'SF (Single Volume)',
 'TFV (Single Volume)',
 'TFI (Single Volume)',
 'VFI (Single Volume)',
 'SFI (Single Volume)',
 'IO',
 'CNS',
 'Skin.1',
 'Bone.1',
 'Muscle.1',
 'AVF (Whole Volume)',
 'SF (Whole Volume)',
 'IO.1',
 'CNS.1',
 'Skin.2',
 'Bone.2',
 'Muscle (Single Area)',
 'SMI (Single Area)',
 'AVF (Single Area)',
 'SF (Single Area)',
 'IO.2',
 'CNS.2',
 'Skin.3',
 'Bone.3',
 'Muscle (Multi Area)',
 'AVF (Multi Area)',
 'SF (Multi Area)',
 'IO.3',
 'CNS.3',
 'Skin.4',
 'Bone.4',
 'Muscle.2',
 'AVF',
 'SF',
 'IO.4',
 'CNS.4',
 'Skin.5',
 'Bone.5',
 'Muscle (Single HU)',
 'AVF (Single HU)',
 'SF (Single HU)',
 'IO.5',
 'CNS.5',
 'Skin.6',
 'Bone.6',
 'Muscle.3',
 'AVF (Multi HU)',
 'SF (Multi HU)',
 'IO.6',
 'CNS.6',
 'AVF/SF Volume Ratio (Single Volume)',
 'Fat Ratio',
 'AVF Index',
 'Total Fat Index',
 'AVF Ratio',
 'Weight-to-Muscle Ratio',
 'Skeletal Muscle Index',
 'Liver/Spleen Volume Ratio',
 'Liver Index',
 'Spleen Index',
 'mean HU(Liver) - mean HU(Spleen)',
 'Liver/Spleen HU Ratio',
 'Liver Fat (PDFF)',
 'Liver',
 'Spleen (Volume)',
 'Liver.1',
 'Spleen']

In [127]:
print(df.columns.tolist())

['Unnamed: 0', '(실명)등록번호', '생년월일', '성별', '병리진단', 'Steatosis score', 'Fibrosis stage', 'Ballooning/Inflammation Score', 'NAFLD Type', 'Smoking', 'HCC', 'HCC_date', 'LRE', 'LRE_date', 'Ascites', 'Ascites_Date', 'Varix bleeding', 'VB_date', 'HEP', 'HEP_date', 'HRS', 'HRS_date', 'LT', 'LT_date', '사망일자', 'CT_B date', 'FS_date', 'LSM', 'CAP', 'AST', 'ALT', 'T.bil', 'PLT', 'PT INR', 'Alb', 'Glucose', 'HbA1c', 'eGFR', 'T.chol', 'HDL', 'LDL', 'TG', 'Weight', 'Height', 'BMI', 'SBP (수축기 혈압) mmHg', 'SBP (수축기 혈압)_date', 'DBP (이완기 혈압) mmHg', 'DBP (이완기 혈압)_date', 'Waist (허리 둘레 cm)', 'Waist (허리 둘레 cm)_date', '음주 여부', '술의 종류', '1회 음주량 (잔 혹은 병)', '음주 횟수 (회/주)', 'CT_1y date', 'FS_date.1', 'LSM.1', 'CAP.1', 'AST.1', 'ALT.1', 'T.bil.1', 'PLT.1', 'PT INR.1', 'Alb.1', 'Glucose.1', 'HbA1c.1', 'eGFR.1', 'T.chol.1', 'HDL.1', 'LDL.1', 'TG.1', 'Inbody_date', 'Weight.1', 'Height.1', 'BMI.1', 'CT_2y date', 'FS_date.2', 'LSM.2', 'CAP.2', 'AST.2', 'ALT.2', 'T.bil.2', 'PLT.2', 'PT INR.2', 'Alb.2', 'Glucose.2', 'HbA1c.2', 'eGFR.2', 'T.chol.2', 'HDL.2', 'LDL.2', 'TG.2', 'Inbody_date.1', 'Weight.2', 'Height.2', 'BMI.2', 'CT_3y date', 'FS_date.3', 'LSM.3', 'CAP.3', 'AST.3', 'ALT.3', 'T.bil.3', 'PLT.3', 'PT INR.3', 'Alb.3', 'Glucose.3', 'HbA1c.3', 'eGFR.3', 'T.chol.3', 'HDL.3', 'LDL.3', 'TG.3', 'Inbody_date.2', 'Weight.3', 'Height.3', 'Unnamed: 117', 'BMI.3', 'CT_4y date', 'FS_date.4', 'LSM.4', 'CAP.4', 'AST.4', 'ALT.4', 'T.bil.4', 'PLT.4', 'PT INR.4', 'Alb.4', 'Glucose.4', 'HbA1c.4', 'eGFR.4', 'T.chol.4', 'HDL.4', 'LDL.4', 'TG.4', 'Inbody_date.3', 'Weight.4', 'Height.4', 'Unnamed: 139', 'BMI.4', 'CT_5y date', 'FS_date.5', 'LSM.5', 'CAP.5', 'AST.5', 'ALT.5', 'T.bil.5', 'PLT.5', 'PT INR.5', 'Alb.5', 'Glucose.5', 'HbA1c.5', 'eGFR.5', 'T.chol.5', 'HDL.5', 'LDL.5', 'TG.5', 'Inbody_date.4', 'Weight.5', 'Height.5', 'Unnamed: 161', 'BMI.5', '당뇨병/당뇨병 전단계 유무', '고혈압유무', '이상지질혈증 유무', 'Ischemic Heart Diseae 유무', 'Cerebrovascualr disease 유무', 'Nephropathy 유무', '당뇨병/당뇨병 전단계 유무.1', '고혈압유무.1', '이상지질혈증 유무.1', 'Ischemic Heart Diseae 유무.1', 'Cerebrovascualr disease 유무.1', 'Nephropathy 유무.1', '당뇨병/당뇨병 전단계 유무.2', '고혈압유무.2', '이상지질혈증 유무.2', 'Ischemic Heart Diseae 유무.2', 'Cerebrovascualr disease 유무.2', 'Nephropathy 유무.2', '당뇨병/당뇨병 전단계 유무.3', '고혈압유무.3', '이상지질혈증 유무.3', 'Ischemic Heart Diseae 유무.3', 'Cerebrovascualr disease 유무.3', 'Nephropathy 유무.3', '당뇨병/당뇨병 전단계 유무.4', '고혈압유무.4', '이상지질혈증 유무.4', 'Ischemic Heart Diseae 유무.4', 'Cerebrovascualr disease 유무.4', 'Nephropathy 유무.4', '당뇨병/당뇨병 전단계 유무.5', '고혈압유무.5', '이상지질혈증 유무.5', 'Ischemic Heart Diseae 유무.5', 'Cerebrovascualr disease 유무.5', 'Nephropathy 유무.5', 'Last fu_date', 'Metformin', 'Metformin_date', 'Dipeptidyl peptidase 4 inhibitor', 'Dipeptidyl peptidase 4 inhibitor_date', 'Sulfonylurea', 'Sulfonylurea_date', 'Thiazolidinedione', 'Thiazolidinedione_date', 'α glucosidase inhibitor', 'α glucosidase inhibitor-date', 'Meglitinide', 'Meglitinide_date', 'SGLT2i', 'SGLT2i_date', 'GLP1 receptor agonist', 'GLP1 receptor agonist_date', 'Insulin', 'Insulin_date', 'ACEi inhibitor', 'ACEi inhibitor_date', 'ARB', 'ARB_date', 'β-adrenergic blocking agents', 'β-adrenergic blocking agents_date', 'α-adrenergic blocking agents', 'α-adrenergic blocking agents_date', 'Cacium channel blocker', 'Cacium channel blocker_date', 'Diuretics_date', 'Diuretics', 'Statin', 'Statin_date', 'fibric acids (fenofibrate)', 'fibric acids (fenofibrate)_date', 'Azetidinone(Cholesterol absorption inhibitors, ezetimibe)', 'VFI', 'SFI', 'SMI', 'Height 2', 'BMI[kg/m2]', 'Circumference [mm]', 'Max Length (L-R) [mm]', 'Max Length (A-P) [mm]', 'Skin', 'Bone', 'Muscle', 'AVF (Single Volume)', 'SF (Single Volume)', 'TFV (Single Volume)', 'TFI (Single Volume)', 'VFI (Single Volume)', 'SFI (Single Volume)', 'IO', 'CNS', 'Skin.1', 'Bone.1', 'Muscle.1', 'AVF (Whole Volume)', 'SF (Whole Volume)', 'IO.1', 'CNS.1', 'Skin.2', 'Bone.2', 'Muscle (Single Area)', 'SMI (Single Area)', 'AVF (Single Area)', 'SF (Single Area)', 'IO.2', 'CNS.2', 'Skin.3', 'Bone.3', 'Muscle (Multi Area)', 'AVF (Multi Area)', 'SF (Multi Area)', 'IO.3', 'CNS.3', 'Skin.4', 'Bone.4', 'Muscle.2', 'AVF', 'SF', 'IO.4', 'CNS.4', 'Skin.5', 'Bone.5', 'Muscle (Single HU)', 'AVF (Single HU)', 'SF (Single HU)', 'IO.5', 'CNS.5', 'Skin.6', 'Bone.6', 'Muscle.3', 'AVF (Multi HU)', 'SF (Multi HU)', 'IO.6', 'CNS.6', 'AVF/SF Volume Ratio (Single Volume)', 'Fat Ratio', 'AVF Index', 'Total Fat Index', 'AVF Ratio', 'Weight-to-Muscle Ratio', 'Skeletal Muscle Index', 'Liver/Spleen Volume Ratio', 'Liver Index', 'Spleen Index', 'mean HU(Liver) - mean HU(Spleen)', 'Liver/Spleen HU Ratio', 'Liver Fat (PDFF)', 'Liver', 'Spleen (Volume)', 'Liver.1', 'Spleen']

In [128]:
df.shape

(292, 314)

In [129]:
df["Smoking"] = df["Smoking"].fillna(0)

In [130]:
columns_to_fix = [
    "FS_date",
    "LSM",
    "CAP",
    "AST",
    "ALT",
    "T.bil",
    "PLT",
    "PT INR",
    "Alb",
    "Glucose",
    "HbA1c",
    "eGFR",
    "T.chol",
    "HDL",
    "LDL",
    "TG",
    "Weight",
    "Height",
    "BMI",
]

# Apply bfill on a new dataframe
for col in columns_to_fix:
    related_columns = [col] + [
        f"{col}.{i}" for i in range(1, 6)
    ]  # column, column.1, column.2, ..., column.5
    df[col] = df[related_columns].bfill(axis=1)[col]

In [131]:
# Rename and filter columns
columns_to_extract = {
    "(실명)등록번호": "ID",
    "성별": "Sex",
    "생년월일": "Birth Date",
    "Fibrosis stage": "Fibrosis Stage",
    "NAFLD Type": "NAFLD Type",
    "사망일자": "Death Date",
    "Circumference [mm]": "Waist",  #'Waist (허리 둘레 cm)': 'Waist',
    "Last fu_date": "Last F/U",
    "Smoking": "Smoking",
    "Ascites": "Ascites",
    "Ascites_Date": "Ascites_Date",
    "Varix bleeding": "VB",
    "VB_date": "VB_Date",
    "HEP": "HEP",
    "HEP_date": "HEP_Date",
    "HRS": "HRS",
    "HRS_date": "HRS_Date",
    "LT": "LT",
    "LT_date": "LT_Date",
    "SBP (수축기 혈압) mmHg": "SBP",
    "DBP (이완기 혈압) mmHg": "DBP",
    "AVF (Whole Volume)": "VFA (Volume)",
    "SF (Whole Volume)": "SFA (Volume)",
    "Spleen (Volume)": "Spleen (Volume)",
    "AVF (Single Area)": "VFA (Area)",
    "SF (Single Area)": "SFA (Area)",
    "Muscle (Single Area)": "SMA (Area)",
    "AVF (Single HU)": "VFA (Attenuation)",
    "SF (Single HU)": "SFA (Attenuation)",
    "Muscle (Single HU)": "SMA (Attenuation)",
    "Liver/Spleen Volume Ratio": "Liver/Spleen Volume",
    "Liver/Spleen HU Ratio": "Liver/Spleen HU",
    "Liver": "Liver (HU)",
    "Spleen": "Spleen (HU)",
    "Liver Fat (PDFF)": "Liver (PDFF)",
}

# Select the specified ranges and additional columns
cols_ct_b_to_drinking = df.loc[:, "CT_B date":"BMI"].columns.tolist()
cols_diabetes_to_nephropathy = df.loc[
    :, "당뇨병/당뇨병 전단계 유무":"Nephropathy 유무"
].columns.tolist()

# Combine all column groups
all_columns = (
    list(columns_to_extract.keys())
    + cols_ct_b_to_drinking
    + cols_diabetes_to_nephropathy
)

In [132]:
all_columns

['(실명)등록번호',
 '성별',
 '생년월일',
 'Fibrosis stage',
 'NAFLD Type',
 '사망일자',
 'Circumference [mm]',
 'Last fu_date',
 'Smoking',
 'Ascites',
 'Ascites_Date',
 'Varix bleeding',
 'VB_date',
 'HEP',
 'HEP_date',
 'HRS',
 'HRS_date',
 'LT',
 'LT_date',
 'SBP (수축기 혈압) mmHg',
 'DBP (이완기 혈압) mmHg',
 'AVF (Whole Volume)',
 'SF (Whole Volume)',
 'Spleen (Volume)',
 'AVF (Single Area)',
 'SF (Single Area)',
 'Muscle (Single Area)',
 'AVF (Single HU)',
 'SF (Single HU)',
 'Muscle (Single HU)',
 'Liver/Spleen Volume Ratio',
 'Liver/Spleen HU Ratio',
 'Liver',
 'Spleen',
 'Liver Fat (PDFF)',
 'CT_B date',
 'FS_date',
 'LSM',
 'CAP',
 'AST',
 'ALT',
 'T.bil',
 'PLT',
 'PT INR',
 'Alb',
 'Glucose',
 'HbA1c',
 'eGFR',
 'T.chol',
 'HDL',
 'LDL',
 'TG',
 'Weight',
 'Height',
 'BMI',
 '당뇨병/당뇨병 전단계 유무',
 '고혈압유무',
 '이상지질혈증 유무',
 'Ischemic Heart Diseae 유무',
 'Cerebrovascualr disease 유무',
 'Nephropathy 유무']

In [133]:
# Filter the DataFrame to keep only these columns
filtered_df = df[all_columns]

# Rename specified columns
filtered_df = filtered_df.rename(columns=columns_to_extract)

# Create Death and Death Date columns based on the 사망일자 column
filtered_df["Death"] = filtered_df["Death Date"].apply(lambda x: 0 if x == 0 else 1)
filtered_df["Death Date"] = filtered_df["Death Date"].apply(
    lambda x: 0 if x == 0 else x
)

In [134]:
filtered_df.columns

Index(['ID', 'Sex', 'Birth Date', 'Fibrosis Stage', 'NAFLD Type', 'Death Date',
       'Waist', 'Last F/U', 'Smoking', 'Ascites', 'Ascites_Date', 'VB',
       'VB_Date', 'HEP', 'HEP_Date', 'HRS', 'HRS_Date', 'LT', 'LT_Date', 'SBP',
       'DBP', 'VFA (Volume)', 'SFA (Volume)', 'Spleen (Volume)', 'VFA (Area)',
       'SFA (Area)', 'SMA (Area)', 'VFA (Attenuation)', 'SFA (Attenuation)',
       'SMA (Attenuation)', 'Liver/Spleen Volume', 'Liver/Spleen HU',
       'Liver (HU)', 'Spleen (HU)', 'Liver (PDFF)', 'CT_B date', 'FS_date',
       'LSM', 'CAP', 'AST', 'ALT', 'T.bil', 'PLT', 'PT INR', 'Alb', 'Glucose',
       'HbA1c', 'eGFR', 'T.chol', 'HDL', 'LDL', 'TG', 'Weight', 'Height',
       'BMI', '당뇨병/당뇨병 전단계 유무', '고혈압유무', '이상지질혈증 유무',
       'Ischemic Heart Diseae 유무', 'Cerebrovascualr disease 유무',
       'Nephropathy 유무', 'Death'],
      dtype='object')

In [135]:
import pandas as pd
import numpy as np

# Step 1: Convert all relevant date columns to datetime format
date_columns = [
    "CT_B date",
    "Ascites_Date",
    "VB_Date",
    "HEP_Date",
    "HRS_Date",
    "LT_Date",
]
for col in date_columns:
    filtered_df[col] = pd.to_datetime(filtered_df[col], errors="coerce")


# Step 2: Define a function to find the first LRE event after CT_B date
def find_first_lre(row):
    event_types = {
        1: "Ascites_Date",
        2: "VB_Date",
        3: "HEP_Date",
        4: "HRS_Date",
        5: "LT_Date",
    }

    # Store event dates that occur after CT_B date
    valid_events = {
        event_id: row[event_date]
        for event_id, event_date in event_types.items()
        if pd.notna(row[event_date]) and row[event_date] > row["CT_B date"]
    }

    if valid_events:
        # Find the earliest event
        first_event_id = min(valid_events, key=valid_events.get)
        first_event_date = valid_events[first_event_id]
        return first_event_id, first_event_date
    else:
        return 0, 0  # No event occurred after CT_B date


# Apply the function to create LRE and LRE Date
filtered_df[["LRE", "LRE Date"]] = filtered_df.apply(
    lambda row: pd.Series(find_first_lre(row)), axis=1
)

# Convert LRE to integer type (for clarity)
filtered_df["LRE"] = filtered_df["LRE"].astype(
    "Int64"
)  # Keeps NaN as <NA> instead of float NaN

In [136]:
# Step 1: Find unique values in the 'NAFLD Type' column
unique_values = filtered_df["NAFLD Type"].unique()
print("Unique values in 'NAFLD Type':", unique_values)

# Step 2: Define the list of values to filter out
X = [
    "Others (Cancer)",
    "NAFL (+)",
    "Probable NASH (+)",
    "NASH (+)",
    "Missing Biopsy",
]  # Example list of values to remove

# Step 3: Remove rows where 'NAFLD Type' is in the list X
no_cancer_df = filtered_df[~filtered_df["NAFLD Type"].isin(X)]
no_cancer_df = no_cancer_df.reset_index(drop=True)

Unique values in 'NAFLD Type': ['Others (Cancer)' 'None' 'Probable NASH' 'NASH' 'NAFL' 'Cirrhosis'
 'Others' 'NAFL (+)' 'Missing Biopsy' 'Probable NASH (+)' 'NASH (+)']

In [137]:
# NAFLD Type이 NaN인 행만 no_cancer_df에서 출력
no_cancer_df[no_cancer_df["NAFLD Type"].isnull()]

Empty DataFrame
Columns: [ID, Sex, Birth Date, Fibrosis Stage, NAFLD Type, Death Date, Waist, Last F/U, Smoking, Ascites, Ascites_Date, VB, VB_Date, HEP, HEP_Date, HRS, HRS_Date, LT, LT_Date, SBP, DBP, VFA (Volume), SFA (Volume), Spleen (Volume), VFA (Area), SFA (Area), SMA (Area), VFA (Attenuation), SFA (Attenuation), SMA (Attenuation), Liver/Spleen Volume, Liver/Spleen HU, Liver (HU), Spleen (HU), Liver (PDFF), CT_B date, FS_date, LSM, CAP, AST, ALT, T.bil, PLT, PT INR, Alb, Glucose, HbA1c, eGFR, T.chol, HDL, LDL, TG, Weight, Height, BMI, 당뇨병/당뇨병 전단계 유무, 고혈압유무, 이상지질혈증 유무, Ischemic Heart Diseae 유무, Cerebrovascualr disease 유무, Nephropathy 유무, Death, LRE, LRE Date]
Index: []

In [139]:
no_cancer_df["NAFLD Type"].unique()

array(['None', 'Probable NASH', 'NASH', 'NAFL', 'Cirrhosis', 'Others'],
      dtype=object)

In [140]:
import numpy as np

# Update the 'Fibrosis Stage' column
no_cancer_df["NASH"] = np.where(
    no_cancer_df["NAFLD Type"].isin(["NASH", "Cirrhosis"]), "Yes", "No"
)

# Display the updated DataFrame
print(no_cancer_df["NASH"].value_counts())

NASH
No     154
Yes     88
Name: count, dtype: int64

#  NASH인데 Nan, 0 -> 1로 / 그 외 Fibrosis인데 NaN은 다 0으로 바꾸기

In [141]:
no_cancer_df["Fibrosis"] = no_cancer_df["Fibrosis Stage"].copy()

no_cancer_df.loc[no_cancer_df["ID"] == 2886838, "Fibrosis"] = 1
no_cancer_df["Fibrosis"].fillna(0, inplace=True)
no_cancer_df["Fibrosis"] = no_cancer_df["Fibrosis"].replace({"1a": 1, "1b": 1, "1c": 1})

In [142]:
# Step 1: Find unique values in the 'NAFLD Type' column
unique_values = no_cancer_df["Fibrosis"].unique()
print("Unique values in 'Fibrosis Stage':", unique_values)

import numpy as np

# Update the 'Fibrosis Stage' column
no_cancer_df["Fibrosis Stage"] = np.where(
    no_cancer_df["Fibrosis"].isin([2, 3, 4]), "High", "Low"
)

# Display the updated DataFrame
print(no_cancer_df["Fibrosis Stage"].unique())

Unique values in 'Fibrosis Stage': [0 1 3 4 2]
['Low' 'High']

In [144]:
no_cancer_df.head(5)

,ID,Sex,Birth Date,Fibrosis Stage,NAFLD Type,Death Date,Waist,Last F/U,Smoking,Ascites,Ascites_Date,VB,VB_Date,HEP,HEP_Date,HRS,HRS_Date,LT,LT_Date,SBP,DBP,VFA (Volume),SFA (Volume),Spleen (Volume),VFA (Area),SFA (Area),SMA (Area),VFA (Attenuation),SFA (Attenuation),SMA (Attenuation),Liver/Spleen Volume,Liver/Spleen HU,Liver (HU),Spleen (HU),Liver (PDFF),CT_B date,FS_date,LSM,CAP,AST,ALT,T.bil,PLT,PT INR,Alb,Glucose,HbA1c,eGFR,T.chol,HDL,LDL,TG,Weight,Height,BMI,당뇨병/당뇨병 전단계 유무,고혈압유무,이상지질혈증 유무,Ischemic Heart Diseae 유무,Cerebrovascualr disease 유무,Nephropathy 유무,Death,LRE,LRE Date,NASH,Fibrosis
0,543747,F,1947-12-22,Low,None,0,813.200378,2021-01-25,0.0,0,NaT,0,NaT,0,NaT,0,NaT,0,NaT,124.0,85.0,1032.168688,1391.775625,110.074938,106.421807,172.502012,92.514199,-98.940834,-105.830856,24.545614,8.252824,1.347252,908.429000,39.634502,6.522456,2011-07-07,NaT,NaN,NaN,20.0,24.0,1.1,222.0,0.97,4.5,88.0,NaN,80.519,193.0,NaN,NaN,149.0,57.0,160.0,22.265625,0,0,0,0,0,0,0,0,0,No,0
1,556772,F,1952-01-14,Low,None,0,788.306213,2023-10-16,0.0,0,NaT,0,NaT,0,NaT,0,NaT,0,NaT,105.0,74.0,508.070781,1172.271125,143.808031,89.713623,151.592969,82.512139,-102.518898,-114.544617,29.191065,4.939308,1.124264,710.312188,46.704075,7.686099,2017-05-11,2017-03-24,3.4,206.0,24.0,27.0,0.8,285.0,1.05,3.9,138.0,5.6,106.448,215.0,56.0,158.0,108.0,54.0,158.0,21.631149,0,0,1,0,0,0,0,0,0,No,0
2,1124503,M,1980-11-05,Low,Probable NASH,0,849.943909,2021-03-23,0.0,0,NaT,0,NaT,0,NaT,0,NaT,0,NaT,140.0,95.0,1053.408625,1109.963250,175.678844,123.377666,112.070576,196.325938,-104.391289,-106.446663,51.848907,7.628467,0.757789,1340.160250,49.510033,15.822743,2014-07-03,NaT,NaN,NaN,33.0,64.0,1.2,267.0,1.00,4.7,91.0,NaN,94.747,202.0,NaN,NaN,NaN,77.0,172.0,26.027582,0,0,0,0,0,0,0,0,0,No,1
3,1132625,F,1963-08-18,High,NASH,0,696.752563,2023-07-13,0.0,0,NaT,0,NaT,0,NaT,0,NaT,0,NaT,100.0,72.0,367.436000,661.771375,318.200906,63.613037,115.604648,95.390977,-88.249924,-96.067482,26.033854,4.009127,1.143369,1275.707750,37.683739,13.075651,2014-09-02,2014-09-22,10.6,200.0,60.0,44.0,0.6,104.0,1.25,2.4,110.0,NaN,150.751,135.0,16.0,97.0,163.0,46.0,153.0,19.650562,0,0,0,0,0,0,0,0,0,Yes,3
4,1196873,F,1944-09-13,Low,NAFL,0,827.678711,2021-03-05,0.0,0,NaT,0,NaT,0,NaT,0,NaT,0,NaT,134.0,76.0,778.699562,880.497562,82.088250,149.392520,140.085840,82.569297,-93.448448,-96.387665,33.130249,13.770583,1.307483,1130.403125,44.377441,5.694679,2015-08-21,2015-08-25,6.4,191.0,19.0,18.0,0.6,297.0,0.87,4.5,145.0,5.5,82.726,161.0,34.0,47.0,69.0,57.0,155.0,23.725286,0,0,1,0,1,0,0,0,0,No,0

In [145]:
no_cancer_df.shape

(242, 66)

In [62]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [146]:
# NAFLD Type이 NaN인 행만 no_cancer_df에서 출력
no_cancer_df[no_cancer_df["NAFLD Type"].isnull()]

Empty DataFrame
Columns: [ID, Sex, Birth Date, Fibrosis Stage, NAFLD Type, Death Date, Waist, Last F/U, Smoking, Ascites, Ascites_Date, VB, VB_Date, HEP, HEP_Date, HRS, HRS_Date, LT, LT_Date, SBP, DBP, VFA (Volume), SFA (Volume), Spleen (Volume), VFA (Area), SFA (Area), SMA (Area), VFA (Attenuation), SFA (Attenuation), SMA (Attenuation), Liver/Spleen Volume, Liver/Spleen HU, Liver (HU), Spleen (HU), Liver (PDFF), CT_B date, FS_date, LSM, CAP, AST, ALT, T.bil, PLT, PT INR, Alb, Glucose, HbA1c, eGFR, T.chol, HDL, LDL, TG, Weight, Height, BMI, 당뇨병/당뇨병 전단계 유무, 고혈압유무, 이상지질혈증 유무, Ischemic Heart Diseae 유무, Cerebrovascualr disease 유무, Nephropathy 유무, Death, LRE, LRE Date, NASH, Fibrosis]
Index: []

In [147]:
# Count rows with NaN values for each column
na_counts = no_cancer_df.isna().sum()

na_counts

ID                              0
Sex                             0
Birth Date                      0
Fibrosis Stage                  0
NAFLD Type                      0
Death Date                      0
Waist                           0
Last F/U                        0
Smoking                         0
Ascites                         0
Ascites_Date                  221
VB                              0
VB_Date                       239
HEP                             0
HEP_Date                      191
HRS                             0
HRS_Date                      242
LT                              0
LT_Date                       229
SBP                             1
DBP                             2
VFA (Volume)                    0
SFA (Volume)                    0
Spleen (Volume)                 0
VFA (Area)                      0
SFA (Area)                      0
SMA (Area)                      0
VFA (Attenuation)               1
SFA (Attenuation)               0
SMA (Attenuation)               0
Liver/Spleen Volume             0
Liver/Spleen HU                 0
Liver (HU)                      0
Spleen (HU)                     0
Liver (PDFF)                    0
CT_B date                       0
FS_date                        42
LSM                            42
CAP                            42
AST                             0
ALT                             0
T.bil                           0
PLT                             0
PT INR                          8
Alb                             0
Glucose                         0
HbA1c                         109
eGFR                            0
T.chol                          1
HDL                            45
LDL                           132
TG                             33
Weight                          0
Height                          0
BMI                             0
당뇨병/당뇨병 전단계 유무                  0
고혈압유무                           0
이상지질혈증 유무                       0
Ischemic Heart Diseae 유무        0
Cerebrovascualr disease 유무      0
Nephropathy 유무                  0
Death                           0
LRE                             0
LRE Date                        0
NASH                            0
Fibrosis                        0
dtype: int64

In [148]:
no_cancer_na_df = no_cancer_df.copy()

# Fibrosis Stage 4인데 NASH로 잘못 처리된 사람 바꾸기

In [149]:
no_cancer_na_df.loc[no_cancer_na_df["ID"] == 1937295, "NAFLD Type"] = "Cirrhosis"

In [150]:
import pandas as pd

# Set pandas display options to show full rows and columns
pd.set_option("display.max_rows", None)  # Show all rows
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.expand_frame_repr", False)  # Prevent column wrapping

# Count null values for each row
null_counts = no_cancer_na_df.isnull().sum(axis=0)

# Add the null count as a new column
null_counts

ID                              0
Sex                             0
Birth Date                      0
Fibrosis Stage                  0
NAFLD Type                      0
Death Date                      0
Waist                           0
Last F/U                        0
Smoking                         0
Ascites                         0
Ascites_Date                  221
VB                              0
VB_Date                       239
HEP                             0
HEP_Date                      191
HRS                             0
HRS_Date                      242
LT                              0
LT_Date                       229
SBP                             1
DBP                             2
VFA (Volume)                    0
SFA (Volume)                    0
Spleen (Volume)                 0
VFA (Area)                      0
SFA (Area)                      0
SMA (Area)                      0
VFA (Attenuation)               1
SFA (Attenuation)               0
SMA (Attenuation)               0
Liver/Spleen Volume             0
Liver/Spleen HU                 0
Liver (HU)                      0
Spleen (HU)                     0
Liver (PDFF)                    0
CT_B date                       0
FS_date                        42
LSM                            42
CAP                            42
AST                             0
ALT                             0
T.bil                           0
PLT                             0
PT INR                          8
Alb                             0
Glucose                         0
HbA1c                         109
eGFR                            0
T.chol                          1
HDL                            45
LDL                           132
TG                             33
Weight                          0
Height                          0
BMI                             0
당뇨병/당뇨병 전단계 유무                  0
고혈압유무                           0
이상지질혈증 유무                       0
Ischemic Heart Diseae 유무        0
Cerebrovascualr disease 유무      0
Nephropathy 유무                  0
Death                           0
LRE                             0
LRE Date                        0
NASH                            0
Fibrosis                        0
dtype: int64

# 괄호 안에 숫자가 기재되어있거나 앞에 부등호가 있는 경우 처리하기

In [151]:
no_cancer_na_df.loc[no_cancer_na_df["ID"] == 5163172, "Alb"] = 4.17
no_cancer_na_df.loc[no_cancer_na_df["ID"] == 4303458, "Alb"] = 3.52

In [152]:
import pandas as pd
import re


# Function to extract only numeric values from a string
def extract_numeric(value):
    if pd.isna(value):  # Keep NaN values unchanged
        return value
    match = re.search(
        r"[-+]?\d*\.?\d+", str(value)
    )  # Extract number (integer or decimal)
    return (
        float(match.group()) if match else None
    )  # Convert to float if found, else None


fill_columns = [
    "SBP",
    "DBP",
    "VFA (Attenuation)",
    "LSM",
    "CAP",
    "ALT",
    "PT INR",
    "HbA1c",
    "T.chol",
    "HDL",
    "LDL",
    "TG",
]  # Add more column names if needed


# Apply this function to each column in fill_columns
for col in fill_columns:
    no_cancer_na_df[col] = no_cancer_na_df[col].apply(extract_numeric)

In [153]:
# Loop through each column in fill_columns and fill NaN with the column median
for (
    col
) in fill_columns:  # Create a new name (e.g., "SBP" from "SBP (수축기 혈압) mmHg")
    no_cancer_na_df[col] = no_cancer_na_df[col].fillna(no_cancer_na_df[col].median())

In [154]:
import pandas as pd

# Set pandas display options to show full rows and columns
pd.set_option("display.max_rows", None)  # Show all rows
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.expand_frame_repr", False)  # Prevent column wrapping

# Count null values for each row
null_counts = no_cancer_na_df.isnull().sum(axis=0)

# Add the null count as a new column
null_counts

ID                              0
Sex                             0
Birth Date                      0
Fibrosis Stage                  0
NAFLD Type                      0
Death Date                      0
Waist                           0
Last F/U                        0
Smoking                         0
Ascites                         0
Ascites_Date                  221
VB                              0
VB_Date                       239
HEP                             0
HEP_Date                      191
HRS                             0
HRS_Date                      242
LT                              0
LT_Date                       229
SBP                             0
DBP                             0
VFA (Volume)                    0
SFA (Volume)                    0
Spleen (Volume)                 0
VFA (Area)                      0
SFA (Area)                      0
SMA (Area)                      0
VFA (Attenuation)               0
SFA (Attenuation)               0
SMA (Attenuation)               0
Liver/Spleen Volume             0
Liver/Spleen HU                 0
Liver (HU)                      0
Spleen (HU)                     0
Liver (PDFF)                    0
CT_B date                       0
FS_date                        42
LSM                             0
CAP                             0
AST                             0
ALT                             0
T.bil                           0
PLT                             0
PT INR                          0
Alb                             0
Glucose                         0
HbA1c                           0
eGFR                            0
T.chol                          0
HDL                             0
LDL                             0
TG                              0
Weight                          0
Height                          0
BMI                             0
당뇨병/당뇨병 전단계 유무                  0
고혈압유무                           0
이상지질혈증 유무                       0
Ischemic Heart Diseae 유무        0
Cerebrovascualr disease 유무      0
Nephropathy 유무                  0
Death                           0
LRE                             0
LRE Date                        0
NASH                            0
Fibrosis                        0
dtype: int64

In [42]:
# Drop rows with NaN in the specified columns
# no_cancer_na_df = no_cancer_df.dropna().reset_index(drop=True)

In [43]:
# no_cancer_na_df.shape

In [155]:
# Save the DataFrame to a CSV file
output_path = "./1st Preprocessing.csv"  # Replace with your desired file path and name
no_cancer_na_df.to_csv(output_path, index=False)